config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts,    only: [:new, :create, :index]
  root   'posts#index'
  get 	 '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_create :create_remember_token
  has_many :posts
  VALID_EMAIL_REGEX = /[A-Z0-9._%+-]+@(?:[A-Z0-9-]+\.)+[A-Z]{2,}/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.new_remember_token
  	SecureRandom.urlsafe_base64
  end

  def User.digest(token)
  	Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

  def new
  	@post = Post.new 
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id 
  	@post.save 
  	redirect_to root_path
  end

  def index
  	@posts = Post.all
  end

  private

    def signed_in_user
  	  unless signed_in?
  	    redirect_to signin_url
  	  end
    end

    def post_params 
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  	  flash[:success] = 'Thanks for signing in'
  	  sign_in user 
  	  redirect_to root_path
  	else
  	  flash.now[:danger] = 'Invalid email/password'
  	  render 'new'
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
  	remember_token = User.new_remember_token
  	cookies.permanent[:remember_token] = remember_token
  	user.update_attribute(:remember_token, User.digest(remember_token))
  	self.current_user = user 
  end

  def current_user=(user)
  	@current_user = user 
  end

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
  	!current_user.nil?
  end

  def sign_out
  	current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
  	cookies.delete(:remember_token)
  	self.current_user = nil
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div>
  <% if signed_in? %>
    <%= link_to "(#{current_user.name}) Sign Out", signout_path, method: "delete" %>
  <% else %>
    <%= link_to "Sign In", signin_path %>
  <% end %>
</div>

<h1>Secret Posts</h1>

<% @posts.each do |post| %>
  <% if signed_in? %>
    <p>
      <%= post.user.name %>
    </p>
  <% end %> 

  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
<% end %>

<% if signed_in? %>
  <%= link_to "New Post", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1 class="text-center">New Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @post do |f| %>

    <p>
      <%= f.label :title %> <br />
      <%= f.text_field :title %>
    </p>

    <p class="form-group">
      <%= f.label :body %><br />
      <textarea class="form-control" rows="5"></textarea>
    </p>

    <p>
      <%= f.submit %>
    </p>

    <% end %>
  </div>
</div>